version: '3.7'

services:

  python:
    user: "1000:1000"
    build: ./python
    image: python_dev:latest
    container_name: python_dev
    volumes:
      - ./python/home/dev/app/:/home/dev/app/
      - ./python/home/dev/.vscode-server/:/home/dev/.vscode-server/
    environment:
      - DEBUG=1
    tty: true
    stdin_open: true
